import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import NavBar from '@/Components/NavBar/NavBar';
import { ToastContainer } from 'react-toastify';
import NextAuthProvider from '@/provider/NextAuthProvider';
import TanstackQuery from '@/provider/TanstackQuery';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <TanstackQuery>
            <NavBar></NavBar>
            {children}
            <ToastContainer />
          </TanstackQuery>
        </body>
      </html>
    </NextAuthProvider>
  );
}
